public with sharing class fukugou {

    public void kurikaeshi(){
        integer intx = 1;
   string sexual = 'female';
        while (intx <= 5) {
            
            system.debug( intx + '回目');
            intx ++;
        system.debug('太郎');
        system.debug('次郎');

        if (sexual == 'male') {
            system.debug('男');
        }else if (sexual == 'female') {
            system.debug('女');
        }else {
            
        } 
        }
    system.debug('こんばんは');        
    }
}